version: '3.8'

services:
  app:
    build: .
    container_name: gps-ingestor-app
    volumes:
      - ./data:/app/data
      - ./main.py:/app/main.py
    networks:
      - gps-network
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: gps-ingestor-nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx-docker.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gps-network
    restart: unless-stopped

networks:
  gps-network:
    driver: bridge

volumes:
  data: